ci:
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.1
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix , "--unsafe-fixes", "--exit-zero" ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.10.3
  hooks:
    - id: uv-lock